Changed needed to compile under GCC 7:
LibArchive/libarchive/archive_match.c:194:41: error: ‘rb_ops_wcs’ defined but not used [-Werror=unused-const-variable=]
 static const struct archive_rb_tree_ops rb_ops_wcs = {
                                          ^~~~~~~~~~